CREATE TABLE IF NOT EXISTS logistics_store_selections (
  token TEXT PRIMARY KEY,
  store_info JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
